version: "3"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:13-alpine
    container_name: template-api-pg
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=template
      - POSTGRES_PASSWORD=template

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: template-api-php
    restart: unless-stopped
    working_dir: /var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    links:
      - postgres

  webserver:
    image: nginx:alpine
    container_name: template-api-webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    links:
      - app
      - postgres
